import type { Play } from '@/types/play'

/*
 * Canonical list of all 39 Shakespeare plays.
 *
 * Field provenance:
 * - id, title, genre, acts, isApocrypha, notableLines: ours
 * - subtitle, serial, pageNumber, yearWritten, characterCount,
 *   approximateRuntime, folioLabel, plate, source: aligned to the
 *   design fixture (data.js) so visual screenshots and live UI agree
 * - approximateRuntime is "uncut full text" minutes; render formatted
 * - plate values are paths under /public; null = placeholder ("PLATE · TO BE COMMISSIONED")
 */

export const PLAYS: Play[] = [
  {
    id: 'hamlet',
    serial: 'SP-1601-HAM',
    pageNumber: 1,
    title: 'Hamlet',
    subtitle: 'Prince of Denmark',
    genre: 'tragedy',
    yearWritten: 1601,
    acts: 5,
    characterCount: 30,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Saxo Grammaticus, Gesta Danorum (c.1200)',
    approximateRuntime: 242,
    notableLines: [
      'To be, or not to be: that is the question.',
      'The play’s the thing wherein I’ll catch the conscience of the king.',
      'There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy.',
    ],
    notableLineRefs: ['3.1', '2.2', '1.5'],
    plate: '/plates/hamlet.svg',
    altTitles: ['Hamlet, Prince of Denmark'],
  },
  {
    id: 'macbeth',
    serial: 'SP-1606-MAC',
    pageNumber: 2,
    title: 'Macbeth',
    subtitle: 'The Scottish Play',
    genre: 'tragedy',
    yearWritten: 1606,
    acts: 5,
    characterCount: 21,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: "Holinshed's Chronicles (1577)",
    approximateRuntime: 148,
    notableLines: [
      'Out, damned spot! Out, I say!',
      'Tomorrow, and tomorrow, and tomorrow, creeps in this petty pace from day to day.',
      'Something wicked this way comes.',
    ],
    plate: '/plates/macbeth.svg',
    altTitles: ['The Scottish Play'],
  },
  {
    id: 'romeo-and-juliet',
    serial: 'SP-1597-ROM',
    pageNumber: 3,
    title: 'Romeo and Juliet',
    subtitle: 'A Tragedy in Verona',
    genre: 'tragedy',
    yearWritten: 1597,
    acts: 5,
    characterCount: 26,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Arthur Brooke, Tragicall Historye (1562)',
    approximateRuntime: 170,
    notableLines: [
      'But, soft! What light through yonder window breaks?',
      'A plague o’ both your houses!',
      'These violent delights have violent ends.',
    ],
    plate: '/plates/romeo-and-juliet.svg',
    altTitles: ['R&J'],
  },
  {
    id: 'king-lear',
    serial: 'SP-1606-LEA',
    pageNumber: 4,
    title: 'King Lear',
    subtitle: 'A Tragedy',
    genre: 'tragedy',
    yearWritten: 1606,
    acts: 5,
    characterCount: 22,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed; Geoffrey of Monmouth',
    approximateRuntime: 210,
    notableLines: [
      'Nothing will come of nothing.',
      'I am a man more sinned against than sinning.',
      'How sharper than a serpent’s tooth it is to have a thankless child!',
    ],
    plate: '/plates/king-lear.svg',
  },
  {
    id: 'othello',
    serial: 'SP-1604-OTH',
    pageNumber: 5,
    title: 'Othello',
    subtitle: 'The Moor of Venice',
    genre: 'tragedy',
    yearWritten: 1604,
    acts: 5,
    characterCount: 16,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Cinthio, Un Capitano Moro (1565)',
    approximateRuntime: 180,
    notableLines: [
      'O, beware, my lord, of jealousy; it is the green-eyed monster.',
      'I will wear my heart upon my sleeve for daws to peck at.',
    ],
    plate: '/plates/othello.svg',
    altTitles: ['The Moor of Venice'],
  },
  {
    id: 'julius-caesar',
    serial: 'SP-1599-JCA',
    pageNumber: 6,
    title: 'Julius Caesar',
    subtitle: 'A Roman Tragedy',
    genre: 'tragedy',
    yearWritten: 1599,
    acts: 5,
    characterCount: 35,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Plutarch, Lives (Thomas North trans., 1579)',
    approximateRuntime: 150,
    notableLines: [
      'Et tu, Brute? Then fall, Caesar.',
      'The fault, dear Brutus, is not in our stars, but in ourselves.',
      'Cowards die many times before their deaths.',
    ],
    plate: '/plates/julius-caesar.svg',
  },
  {
    id: 'antony-and-cleopatra',
    serial: 'SP-1607-ANT',
    pageNumber: 7,
    title: 'Antony and Cleopatra',
    subtitle: 'A Tragedy',
    genre: 'tragedy',
    yearWritten: 1607,
    acts: 5,
    characterCount: 34,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Plutarch, Lives',
    approximateRuntime: 195,
    notableLines: [
      'Age cannot wither her, nor custom stale her infinite variety.',
      'I am dying, Egypt, dying.',
    ],
    plate: '/plates/antony-and-cleopatra.svg',
  },
  {
    id: 'coriolanus',
    serial: 'SP-1608-COR',
    pageNumber: 8,
    title: 'Coriolanus',
    subtitle: 'A Roman Tragedy',
    genre: 'tragedy',
    yearWritten: 1608,
    acts: 5,
    characterCount: 50,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Plutarch, Lives',
    approximateRuntime: 195,
    notableLines: ['I banish you.', 'Nature teaches beasts to know their friends.'],
    plate: '/plates/coriolanus.svg',
  },
  {
    id: 'titus-andronicus',
    serial: 'SP-1594-TIT',
    pageNumber: 9,
    title: 'Titus Andronicus',
    subtitle: 'A Tragedy',
    genre: 'tragedy',
    yearWritten: 1594,
    acts: 5,
    characterCount: 27,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Ovid, Metamorphoses',
    approximateRuntime: 165,
    notableLines: [
      'Vengeance is in my heart, death in my hand, blood and revenge are hammering in my head.',
      'These words are razors to my wounded heart.',
    ],
    plate: null,
  },
  {
    id: 'timon-of-athens',
    serial: 'SP-1606-TIM',
    pageNumber: 10,
    title: 'Timon of Athens',
    subtitle: 'A Tragedy',
    genre: 'tragedy',
    yearWritten: 1606,
    acts: 5,
    characterCount: 54,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Plutarch; Lucian',
    approximateRuntime: 150,
    notableLines: ['I am Misanthropos, and hate mankind.', 'We have seen better days.'],
    plate: null,
  },
  {
    id: 'troilus-and-cressida',
    serial: 'SP-1602-TRO',
    pageNumber: 11,
    title: 'Troilus and Cressida',
    subtitle: 'A Problem Tragedy',
    genre: 'tragedy',
    yearWritten: 1602,
    acts: 5,
    characterCount: 31,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Chaucer; Homer',
    approximateRuntime: 195,
    notableLines: [
      'Take but degree away, untune that string, and hark, what discord follows.',
      'O, beauty, where is thy faith?',
    ],
    plate: null,
  },
  {
    id: 'midsummer-nights-dream',
    serial: 'SP-1595-MND',
    pageNumber: 12,
    title: "A Midsummer Night's Dream",
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1595,
    acts: 5,
    characterCount: 21,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Ovid; Chaucer; Apuleius',
    approximateRuntime: 140,
    notableLines: [
      'The course of true love never did run smooth.',
      'Lord, what fools these mortals be!',
    ],
    plate: '/plates/a-midsummer-nights-dream.svg',
    altTitles: ['Midsummer', 'Dream', 'MND'],
  },
  {
    id: 'much-ado-about-nothing',
    serial: 'SP-1599-MUC',
    pageNumber: 13,
    title: 'Much Ado About Nothing',
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1599,
    acts: 5,
    characterCount: 21,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Bandello, Novelle (1554)',
    approximateRuntime: 150,
    notableLines: [
      'Sigh no more, ladies, sigh no more.',
      'I do love nothing in the world so well as you. Is not that strange?',
    ],
    plate: '/plates/much-ado-about-nothing.svg',
    altTitles: ['Much Ado'],
  },
  {
    id: 'as-you-like-it',
    serial: 'SP-1599-AYL',
    pageNumber: 14,
    title: 'As You Like It',
    subtitle: 'A Pastoral Comedy',
    genre: 'comedy',
    yearWritten: 1599,
    acts: 5,
    characterCount: 26,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Thomas Lodge, Rosalynde (1590)',
    approximateRuntime: 160,
    notableLines: [
      'All the world’s a stage, and all the men and women merely players.',
      'The fool doth think he is wise, but the wise man knows himself to be a fool.',
    ],
    plate: '/plates/as-you-like-it.svg',
    altTitles: ['AYLI'],
  },
  {
    id: 'taming-of-the-shrew',
    serial: 'SP-1592-SHR',
    pageNumber: 15,
    title: 'The Taming of the Shrew',
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1592,
    acts: 5,
    characterCount: 22,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Italian commedia; Gascoigne, Supposes',
    approximateRuntime: 150,
    notableLines: [
      'Kiss me, Kate.',
      'Such duty as the subject owes the prince, even such a woman oweth to her husband.',
    ],
    plate: '/plates/the-taming-of-the-shrew.svg',
    altTitles: ['Shrew'],
  },
  {
    id: 'merchant-of-venice',
    serial: 'SP-1597-MER',
    pageNumber: 16,
    title: 'The Merchant of Venice',
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1597,
    acts: 5,
    characterCount: 19,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Il Pecorone (1558)',
    approximateRuntime: 170,
    notableLines: ['The quality of mercy is not strain’d.', 'If you prick us, do we not bleed?'],
    plate: '/plates/the-merchant-of-venice.svg',
  },
  {
    id: 'twelfth-night',
    serial: 'SP-1601-TWE',
    pageNumber: 17,
    title: 'Twelfth Night',
    subtitle: 'Or, What You Will',
    genre: 'comedy',
    yearWritten: 1601,
    acts: 5,
    characterCount: 14,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Barnabe Riche, Apolonius and Silla (1581)',
    approximateRuntime: 155,
    notableLines: [
      'If music be the food of love, play on.',
      'Some are born great, some achieve greatness, and some have greatness thrust upon them.',
    ],
    plate: null,
    altTitles: ['What You Will'],
  },
  {
    id: 'merry-wives-of-windsor',
    serial: 'SP-1597-MWW',
    pageNumber: 18,
    title: 'The Merry Wives of Windsor',
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1597,
    acts: 5,
    characterCount: 20,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Original',
    approximateRuntime: 145,
    notableLines: [
      'Why, then the world’s mine oyster.',
      'I cannot tell what the dickens his name is.',
    ],
    plate: '/plates/the-merry-wives-of-windsor.svg',
  },
  {
    id: 'comedy-of-errors',
    serial: 'SP-1594-COE',
    pageNumber: 19,
    title: 'The Comedy of Errors',
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1594,
    acts: 5,
    characterCount: 17,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Plautus, Menaechmi',
    approximateRuntime: 110,
    notableLines: [
      'A wretched soul, bruised with adversity, we bid be quiet when we hear it cry.',
      'There’s a time for all things.',
    ],
    plate: '/plates/the-comedy-of-errors.svg',
  },
  {
    id: 'loves-labours-lost',
    serial: 'SP-1595-LLL',
    pageNumber: 20,
    title: "Love's Labour's Lost",
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1595,
    acts: 5,
    characterCount: 16,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Original',
    approximateRuntime: 170,
    notableLines: [
      'They have been at a great feast of languages and stolen the scraps.',
      'When daisies pied and violets blue do paint the meadows with delight.',
    ],
    plate: '/plates/loves-labours-lost.svg',
  },
  {
    id: 'measure-for-measure',
    serial: 'SP-1604-MEA',
    pageNumber: 21,
    title: 'Measure for Measure',
    subtitle: 'A Problem Comedy',
    genre: 'comedy',
    yearWritten: 1604,
    acts: 5,
    characterCount: 22,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Cinthio; George Whetstone',
    approximateRuntime: 165,
    notableLines: [
      'Some rise by sin, and some by virtue fall.',
      'The miserable have no other medicine but only hope.',
    ],
    plate: '/plates/measure-for-measure.svg',
  },
  {
    id: 'two-gentlemen-of-verona',
    serial: 'SP-1591-TGV',
    pageNumber: 22,
    title: 'The Two Gentlemen of Verona',
    subtitle: 'A Comedy',
    genre: 'comedy',
    yearWritten: 1591,
    acts: 5,
    characterCount: 17,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Jorge de Montemayor, Diana',
    approximateRuntime: 130,
    notableLines: [
      'How use doth breed a habit in a man!',
      'Who is Silvia? What is she, that all our swains commend her?',
    ],
    plate: null,
    altTitles: ['TGV'],
  },
  {
    id: 'king-john',
    serial: 'SP-1596-KJN',
    pageNumber: 23,
    title: 'King John',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1596,
    acts: 5,
    characterCount: 27,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'The Troublesome Reign (1591)',
    approximateRuntime: 160,
    notableLines: [
      'Mad world! Mad kings! Mad composition!',
      'To gild refined gold, to paint the lily.',
    ],
    plate: '/plates/king-john.svg',
  },
  {
    id: 'richard-ii',
    serial: 'SP-1595-RII',
    pageNumber: 24,
    title: 'Richard II',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1595,
    acts: 5,
    characterCount: 31,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: "Holinshed's Chronicles",
    approximateRuntime: 175,
    notableLines: [
      'This royal throne of kings, this sceptred isle.',
      'For God’s sake, let us sit upon the ground and tell sad stories of the death of kings.',
    ],
    plate: null,
  },
  {
    id: 'henry-iv-part-1',
    serial: 'SP-1597-H41',
    pageNumber: 25,
    title: 'Henry IV, Part 1',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1597,
    acts: 5,
    characterCount: 33,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed; Famous Victories',
    approximateRuntime: 180,
    notableLines: [
      'The better part of valour is discretion.',
      'Banish plump Jack, and banish all the world.',
    ],
    plate: '/plates/henry-iv-part-1.svg',
    altTitles: ['1 Henry IV'],
  },
  {
    id: 'henry-iv-part-2',
    serial: 'SP-1598-H42',
    pageNumber: 26,
    title: 'Henry IV, Part 2',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1598,
    acts: 5,
    characterCount: 47,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed',
    approximateRuntime: 185,
    notableLines: ['Uneasy lies the head that wears a crown.', 'I know thee not, old man.'],
    plate: '/plates/henry-iv-part-2.svg',
    altTitles: ['2 Henry IV'],
  },
  {
    id: 'henry-v',
    serial: 'SP-1599-HV',
    pageNumber: 27,
    title: 'Henry V',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1599,
    acts: 5,
    characterCount: 41,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed',
    approximateRuntime: 180,
    notableLines: [
      'Once more unto the breach, dear friends, once more.',
      'We few, we happy few, we band of brothers.',
    ],
    plate: '/plates/henry-v.svg',
  },
  {
    id: 'henry-vi-part-1',
    serial: 'SP-1592-H61',
    pageNumber: 28,
    title: 'Henry VI, Part 1',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1592,
    acts: 5,
    characterCount: 50,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed; Hall',
    approximateRuntime: 170,
    notableLines: [
      'Hung be the heavens with black, yield day to night!',
      'Glory is like a circle in the water.',
    ],
    plate: '/plates/henry-vi-part-1.svg',
    altTitles: ['1 Henry VI'],
  },
  {
    id: 'henry-vi-part-2',
    serial: 'SP-1591-H62',
    pageNumber: 29,
    title: 'Henry VI, Part 2',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1591,
    acts: 5,
    characterCount: 60,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed; Hall',
    approximateRuntime: 180,
    notableLines: [
      'The first thing we do, let’s kill all the lawyers.',
      'Small things make base men proud.',
    ],
    plate: '/plates/henry-vi-part-2.svg',
    altTitles: ['2 Henry VI'],
  },
  {
    id: 'henry-vi-part-3',
    serial: 'SP-1591-H63',
    pageNumber: 30,
    title: 'Henry VI, Part 3',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1591,
    acts: 5,
    characterCount: 50,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed; Hall',
    approximateRuntime: 180,
    notableLines: [
      'O tiger’s heart wrapped in a woman’s hide!',
      'Suspicion always haunts the guilty mind.',
    ],
    plate: '/plates/henry-vi-part-3.svg',
    altTitles: ['3 Henry VI'],
  },
  {
    id: 'richard-iii',
    serial: 'SP-1593-RIII',
    pageNumber: 31,
    title: 'Richard III',
    subtitle: 'A History',
    genre: 'history',
    yearWritten: 1593,
    acts: 5,
    characterCount: 52,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Thomas More, History of King Richard III',
    approximateRuntime: 210,
    notableLines: [
      'Now is the winter of our discontent.',
      'A horse! A horse! My kingdom for a horse!',
    ],
    plate: '/plates/richard-iii.svg',
  },
  {
    id: 'henry-viii',
    serial: 'SP-1613-HVIII',
    pageNumber: 32,
    title: 'Henry VIII',
    subtitle: 'All Is True',
    genre: 'history',
    yearWritten: 1613,
    acts: 5,
    characterCount: 47,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed; Foxe (with John Fletcher)',
    approximateRuntime: 180,
    notableLines: [
      'Heat not a furnace for your foe so hot that it do singe yourself.',
      'I have touched the highest point of all my greatness.',
    ],
    plate: '/plates/henry-viii.svg',
    altTitles: ['All Is True'],
  },
  {
    id: 'the-tempest',
    serial: 'SP-1611-TEM',
    pageNumber: 33,
    title: 'The Tempest',
    subtitle: 'A Romance',
    genre: 'romance',
    yearWritten: 1611,
    acts: 5,
    characterCount: 16,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Strachey, True Reportory (1610)',
    approximateRuntime: 150,
    notableLines: [
      'We are such stuff as dreams are made on, and our little life is rounded with a sleep.',
      'O brave new world, that has such people in’t!',
    ],
    plate: null,
    altTitles: ['Tempest'],
  },
  {
    id: 'winters-tale',
    serial: 'SP-1611-WT',
    pageNumber: 34,
    title: "The Winter's Tale",
    subtitle: 'A Romance',
    genre: 'romance',
    yearWritten: 1611,
    acts: 5,
    characterCount: 26,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Robert Greene, Pandosto (1588)',
    approximateRuntime: 185,
    notableLines: ['Exit, pursued by a bear.', 'A sad tale’s best for winter.'],
    plate: null,
  },
  {
    id: 'cymbeline',
    serial: 'SP-1610-CYM',
    pageNumber: 35,
    title: 'Cymbeline',
    subtitle: 'A Romance',
    genre: 'romance',
    yearWritten: 1610,
    acts: 5,
    characterCount: 40,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Holinshed; Boccaccio',
    approximateRuntime: 190,
    notableLines: [
      'Fear no more the heat o’ the sun, nor the furious winter’s rages.',
      'Hang there like fruit, my soul, till the tree die.',
    ],
    plate: '/plates/cymbeline.svg',
  },
  {
    id: 'pericles',
    serial: 'SP-1608-PER',
    pageNumber: 36,
    title: 'Pericles, Prince of Tyre',
    subtitle: 'A Romance',
    genre: 'romance',
    yearWritten: 1608,
    acts: 5,
    characterCount: 50,
    inFirstFolio: false,
    folioLabel: 'Not in First Folio · added 1664',
    source: 'John Gower, Confessio Amantis',
    approximateRuntime: 180,
    notableLines: [
      'O you gods, why do you make us love your goodly gifts and snatch them straight away?',
      'Few love to hear the sins they love to act.',
    ],
    plate: '/plates/pericles.png',
    altTitles: ['Pericles'],
  },
  {
    id: 'alls-well-that-ends-well',
    serial: 'SP-1605-AWE',
    pageNumber: 37,
    title: "All's Well That Ends Well",
    subtitle: 'A Problem Romance',
    genre: 'romance',
    yearWritten: 1605,
    acts: 5,
    characterCount: 24,
    inFirstFolio: true,
    folioLabel: 'First Folio · 1623',
    source: 'Boccaccio, Decameron',
    approximateRuntime: 155,
    notableLines: [
      'All’s well that ends well; still the fine’s the crown.',
      'Love all, trust a few, do wrong to none.',
    ],
    plate: '/plates/alls-well-that-ends-well.png',
  },
  {
    id: 'edward-iii',
    serial: 'SP-1592-E3',
    pageNumber: 38,
    title: 'Edward III',
    subtitle: 'A History · Apocrypha',
    genre: 'apocrypha',
    yearWritten: 1592,
    acts: 5,
    characterCount: 36,
    inFirstFolio: false,
    folioLabel: 'Not in First Folio · attribution 1760',
    source: 'Holinshed; Froissart (collaborative)',
    approximateRuntime: 170,
    notableLines: ['Lilies that fester smell far worse than weeds.', 'A pox of wrinkles!'],
    plate: '/plates/edward-iii.svg',
    altTitles: ['The Reign of King Edward III'],
  },
  {
    id: 'two-noble-kinsmen',
    serial: 'SP-1613-TNK',
    pageNumber: 39,
    title: 'The Two Noble Kinsmen',
    subtitle: 'A Romance · Collab',
    genre: 'apocrypha',
    yearWritten: 1613,
    acts: 5,
    characterCount: 22,
    inFirstFolio: false,
    folioLabel: 'Not in First Folio · attribution 1634',
    source: "Chaucer, Knight's Tale (with John Fletcher)",
    approximateRuntime: 170,
    notableLines: [
      'O, never shall we two enjoy our lives, before we know ourselves.',
      'New plays and maidenheads are near akin.',
    ],
    plate: null,
    altTitles: ['2NK', 'TNK'],
  },
]

export function getPlay(id: string): Play | undefined {
  return PLAYS.find((p) => p.id === id)
}

export function getPlayIds(): string[] {
  return PLAYS.map((p) => p.id)
}

export function getPlayByPage(page: number): Play | undefined {
  return PLAYS.find((p) => p.pageNumber === page)
}

/** Returns adjacent play IDs for next/prev navigation in the book. */
export function getAdjacent(id: string): { prev: Play | null; next: Play | null } {
  const play = getPlay(id)
  if (!play) return { prev: null, next: null }
  return {
    prev: getPlayByPage(play.pageNumber - 1) ?? null,
    next: getPlayByPage(play.pageNumber + 1) ?? null,
  }
}

/** Format minutes as "Xh YYm". */
export function formatRuntime(minutes: number): string {
  const h = Math.floor(minutes / 60)
  const m = minutes % 60
  return `${h}h ${String(m).padStart(2, '0')}m`
}
