import type { Play } from '@/types/play'

/*
 * Canonical list of all 39 Shakespeare plays (Folger canon + Pericles +
 * Two Noble Kinsmen + Edward III). This file is the v1 source of truth.
 *
 * Notes on data provenance:
 * - yearWritten uses Folger / Wells-Taylor-Jowett consensus dating.
 * - characterCount counts named speaking roles in standard editions;
 *   exact totals vary slightly by edition.
 * - approximateRuntime is "as commonly performed" with typical cuts,
 *   not the full uncut text. Productions vary widely.
 * - notableLines kept to 2 per play. Not the most-quoted; chosen to
 *   read well as page hooks.
 * - source describes the principal source(s) Shakespeare drew from.
 * - Apocrypha (Edward III, Two Noble Kinsmen) carry genre 'apocrypha'.
 *   Pericles is genre 'romance' but inFirstFolio = false.
 */

export const PLAYS: Play[] = [
  {
    id: 'alls-well-that-ends-well',
    serial: 'SP-1604-AWW',
    title: "All's Well That Ends Well",
    genre: 'comedy',
    yearWritten: 1604,
    acts: 5,
    characterCount: 19,
    inFirstFolio: true,
    source: "Boccaccio's Decameron (Day 3, Tale 9)",
    approximateRuntime: 165,
    notableLines: [
      'All’s well that ends well; still the fine’s the crown.',
      'Love all, trust a few, do wrong to none.',
    ],
  },
  {
    id: 'antony-and-cleopatra',
    serial: 'SP-1606-ANT',
    title: 'Antony and Cleopatra',
    genre: 'tragedy',
    yearWritten: 1606,
    acts: 5,
    characterCount: 34,
    inFirstFolio: true,
    source: "Plutarch’s Lives (Life of Antony)",
    approximateRuntime: 195,
    notableLines: [
      'Age cannot wither her, nor custom stale her infinite variety.',
      'I am dying, Egypt, dying.',
    ],
  },
  {
    id: 'as-you-like-it',
    serial: 'SP-1599-AYL',
    title: 'As You Like It',
    genre: 'comedy',
    yearWritten: 1599,
    acts: 5,
    characterCount: 22,
    inFirstFolio: true,
    source: "Thomas Lodge’s Rosalynde (1590)",
    approximateRuntime: 150,
    notableLines: [
      'All the world’s a stage, and all the men and women merely players.',
      'The fool doth think he is wise, but the wise man knows himself to be a fool.',
    ],
    altTitles: ['AYLI'],
  },
  {
    id: 'comedy-of-errors',
    serial: 'SP-1592-CoE',
    title: 'The Comedy of Errors',
    genre: 'comedy',
    yearWritten: 1592,
    acts: 5,
    characterCount: 16,
    inFirstFolio: true,
    source: "Plautus’ Menaechmi and Amphitruo",
    approximateRuntime: 105,
    notableLines: [
      'A wretched soul, bruised with adversity, we bid be quiet when we hear it cry.',
      'There’s a time for all things.',
    ],
  },
  {
    id: 'coriolanus',
    serial: 'SP-1607-COR',
    title: 'Coriolanus',
    genre: 'tragedy',
    yearWritten: 1607,
    acts: 5,
    characterCount: 28,
    inFirstFolio: true,
    source: "Plutarch’s Lives (Life of Coriolanus)",
    approximateRuntime: 180,
    notableLines: [
      'I banish you.',
      'Nature teaches beasts to know their friends.',
    ],
  },
  {
    id: 'cymbeline',
    serial: 'SP-1609-CYM',
    title: 'Cymbeline',
    genre: 'romance',
    yearWritten: 1609,
    acts: 5,
    characterCount: 26,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles and Boccaccio’s Decameron",
    approximateRuntime: 195,
    notableLines: [
      'Fear no more the heat o’ the sun, nor the furious winter’s rages.',
      'Hang there like fruit, my soul, till the tree die.',
    ],
  },
  {
    id: 'hamlet',
    serial: 'SP-1600-HAM',
    title: 'Hamlet',
    genre: 'tragedy',
    yearWritten: 1600,
    acts: 5,
    characterCount: 30,
    inFirstFolio: true,
    source: "Saxo Grammaticus and Belleforest; the lost “Ur-Hamlet”",
    approximateRuntime: 210,
    notableLines: [
      'To be, or not to be: that is the question.',
      'The play’s the thing wherein I’ll catch the conscience of the king.',
    ],
    altTitles: ['Hamlet, Prince of Denmark'],
  },
  {
    id: 'henry-iv-part-1',
    serial: 'SP-1596-1H4',
    title: 'Henry IV, Part 1',
    genre: 'history',
    yearWritten: 1596,
    acts: 5,
    characterCount: 32,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; Daniel’s Civil Wars",
    approximateRuntime: 180,
    notableLines: [
      'The better part of valour is discretion.',
      'Banish plump Jack, and banish all the world.',
    ],
    altTitles: ['1 Henry IV', 'Henry IV Part One'],
  },
  {
    id: 'henry-iv-part-2',
    serial: 'SP-1598-2H4',
    title: 'Henry IV, Part 2',
    genre: 'history',
    yearWritten: 1598,
    acts: 5,
    characterCount: 36,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; Daniel’s Civil Wars",
    approximateRuntime: 180,
    notableLines: [
      'Uneasy lies the head that wears a crown.',
      'I know thee not, old man.',
    ],
    altTitles: ['2 Henry IV', 'Henry IV Part Two'],
  },
  {
    id: 'henry-v',
    serial: 'SP-1599-H5',
    title: 'Henry V',
    genre: 'history',
    yearWritten: 1599,
    acts: 5,
    characterCount: 35,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; The Famous Victories of Henry V",
    approximateRuntime: 180,
    notableLines: [
      'Once more unto the breach, dear friends, once more.',
      'We few, we happy few, we band of brothers.',
    ],
  },
  {
    id: 'henry-vi-part-1',
    serial: 'SP-1591-1H6',
    title: 'Henry VI, Part 1',
    genre: 'history',
    yearWritten: 1591,
    acts: 5,
    characterCount: 38,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; Hall’s Union",
    approximateRuntime: 165,
    notableLines: [
      'Hung be the heavens with black, yield day to night!',
      'Glory is like a circle in the water.',
    ],
    altTitles: ['1 Henry VI'],
  },
  {
    id: 'henry-vi-part-2',
    serial: 'SP-1590-2H6',
    title: 'Henry VI, Part 2',
    genre: 'history',
    yearWritten: 1590,
    acts: 5,
    characterCount: 42,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; Hall’s Union",
    approximateRuntime: 180,
    notableLines: [
      'The first thing we do, let’s kill all the lawyers.',
      'Small things make base men proud.',
    ],
    altTitles: ['2 Henry VI'],
  },
  {
    id: 'henry-vi-part-3',
    serial: 'SP-1591-3H6',
    title: 'Henry VI, Part 3',
    genre: 'history',
    yearWritten: 1591,
    acts: 5,
    characterCount: 36,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; Hall’s Union",
    approximateRuntime: 180,
    notableLines: [
      'O tiger’s heart wrapped in a woman’s hide!',
      'Suspicion always haunts the guilty mind.',
    ],
    altTitles: ['3 Henry VI'],
  },
  {
    id: 'henry-viii',
    serial: 'SP-1613-H8',
    title: 'Henry VIII',
    genre: 'history',
    yearWritten: 1613,
    acts: 5,
    characterCount: 38,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; Foxe’s Acts and Monuments",
    approximateRuntime: 180,
    notableLines: [
      'Heat not a furnace for your foe so hot that it do singe yourself.',
      'I have touched the highest point of all my greatness.',
    ],
    altTitles: ['All Is True'],
  },
  {
    id: 'julius-caesar',
    serial: 'SP-1599-JC',
    title: 'Julius Caesar',
    genre: 'tragedy',
    yearWritten: 1599,
    acts: 5,
    characterCount: 30,
    inFirstFolio: true,
    source: "Plutarch’s Lives (Caesar, Brutus, Antony)",
    approximateRuntime: 150,
    notableLines: [
      'Et tu, Brute? Then fall, Caesar.',
      'The fault, dear Brutus, is not in our stars, but in ourselves.',
    ],
  },
  {
    id: 'king-john',
    serial: 'SP-1595-KJ',
    title: 'King John',
    genre: 'history',
    yearWritten: 1595,
    acts: 5,
    characterCount: 22,
    inFirstFolio: true,
    source: "The Troublesome Reign of King John (anon., 1591)",
    approximateRuntime: 165,
    notableLines: [
      'Mad world! Mad kings! Mad composition!',
      'To gild refined gold, to paint the lily.',
    ],
  },
  {
    id: 'king-lear',
    serial: 'SP-1605-KL',
    title: 'King Lear',
    genre: 'tragedy',
    yearWritten: 1605,
    acts: 5,
    characterCount: 24,
    inFirstFolio: true,
    source: "The True Chronicle History of King Leir; Holinshed",
    approximateRuntime: 195,
    notableLines: [
      'Nothing will come of nothing.',
      'How sharper than a serpent’s tooth it is to have a thankless child!',
    ],
  },
  {
    id: 'loves-labours-lost',
    serial: 'SP-1593-LLL',
    title: "Love's Labour's Lost",
    genre: 'comedy',
    yearWritten: 1593,
    acts: 5,
    characterCount: 18,
    inFirstFolio: true,
    source: "No known principal source; topical and original",
    approximateRuntime: 165,
    notableLines: [
      'They have been at a great feast of languages and stolen the scraps.',
      'When daisies pied and violets blue do paint the meadows with delight.',
    ],
  },
  {
    id: 'macbeth',
    serial: 'SP-1606-MAC',
    title: 'Macbeth',
    genre: 'tragedy',
    yearWritten: 1606,
    acts: 5,
    characterCount: 22,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles (Scottish history)",
    approximateRuntime: 150,
    notableLines: [
      'Out, damned spot! Out, I say!',
      'Tomorrow, and tomorrow, and tomorrow, creeps in this petty pace from day to day.',
    ],
    altTitles: ['The Scottish Play'],
  },
  {
    id: 'measure-for-measure',
    serial: 'SP-1603-MFM',
    title: 'Measure for Measure',
    genre: 'comedy',
    yearWritten: 1603,
    acts: 5,
    characterCount: 20,
    inFirstFolio: true,
    source: "Cinthio’s Hecatommithi; Whetstone’s Promos and Cassandra",
    approximateRuntime: 165,
    notableLines: [
      'Some rise by sin, and some by virtue fall.',
      'The miserable have no other medicine but only hope.',
    ],
  },
  {
    id: 'merchant-of-venice',
    serial: 'SP-1596-MoV',
    title: 'The Merchant of Venice',
    genre: 'comedy',
    yearWritten: 1596,
    acts: 5,
    characterCount: 21,
    inFirstFolio: true,
    source: "Il Pecorone (Giovanni Fiorentino, 14th c.)",
    approximateRuntime: 165,
    notableLines: [
      'The quality of mercy is not strain’d.',
      'If you prick us, do we not bleed?',
    ],
  },
  {
    id: 'merry-wives-of-windsor',
    serial: 'SP-1597-MWW',
    title: 'The Merry Wives of Windsor',
    genre: 'comedy',
    yearWritten: 1597,
    acts: 5,
    characterCount: 20,
    inFirstFolio: true,
    source: "No principal source; Italian novelle as influence",
    approximateRuntime: 150,
    notableLines: [
      'Why, then the world’s mine oyster.',
      'I cannot tell what the dickens his name is.',
    ],
  },
  {
    id: 'midsummer-nights-dream',
    serial: 'SP-1595-MND',
    title: "A Midsummer Night's Dream",
    genre: 'comedy',
    yearWritten: 1595,
    acts: 5,
    characterCount: 21,
    inFirstFolio: true,
    source: "Original; influences from Ovid, Apuleius, Chaucer",
    approximateRuntime: 135,
    notableLines: [
      'The course of true love never did run smooth.',
      'Lord, what fools these mortals be!',
    ],
    altTitles: ['Midsummer', 'Dream', 'MND'],
  },
  {
    id: 'much-ado-about-nothing',
    serial: 'SP-1598-MAN',
    title: 'Much Ado About Nothing',
    genre: 'comedy',
    yearWritten: 1598,
    acts: 5,
    characterCount: 21,
    inFirstFolio: true,
    source: "Bandello’s Novelle; Ariosto’s Orlando Furioso",
    approximateRuntime: 150,
    notableLines: [
      'Sigh no more, ladies, sigh no more.',
      'I do love nothing in the world so well as you. Is not that strange?',
    ],
    altTitles: ['Much Ado'],
  },
  {
    id: 'othello',
    serial: 'SP-1603-OTH',
    title: 'Othello',
    genre: 'tragedy',
    yearWritten: 1603,
    acts: 5,
    characterCount: 17,
    inFirstFolio: true,
    source: "Cinthio’s Hecatommithi (Tale 7)",
    approximateRuntime: 180,
    notableLines: [
      'O, beware, my lord, of jealousy; it is the green-eyed monster.',
      'I have done the state some service, and they know’t.',
    ],
    altTitles: ['The Moor of Venice'],
  },
  {
    id: 'pericles',
    serial: 'SP-1607-PER',
    title: 'Pericles, Prince of Tyre',
    genre: 'romance',
    yearWritten: 1607,
    acts: 5,
    characterCount: 28,
    inFirstFolio: false,
    source: "John Gower’s Confessio Amantis; Twine’s Pattern of Painful Adventures",
    approximateRuntime: 165,
    notableLines: [
      'O you gods, why do you make us love your goodly gifts and snatch them straight away?',
      'Few love to hear the sins they love to act.',
    ],
    altTitles: ['Pericles'],
  },
  {
    id: 'richard-ii',
    serial: 'SP-1594-R2',
    title: 'Richard II',
    genre: 'history',
    yearWritten: 1594,
    acts: 5,
    characterCount: 25,
    inFirstFolio: true,
    source: "Holinshed’s Chronicles; Daniel’s Civil Wars",
    approximateRuntime: 165,
    notableLines: [
      'This royal throne of kings, this sceptred isle.',
      'For God’s sake, let us sit upon the ground and tell sad stories of the death of kings.',
    ],
  },
  {
    id: 'richard-iii',
    serial: 'SP-1592-R3',
    title: 'Richard III',
    genre: 'history',
    yearWritten: 1592,
    acts: 5,
    characterCount: 38,
    inFirstFolio: true,
    source: "Holinshed; Hall; Thomas More’s History of King Richard III",
    approximateRuntime: 195,
    notableLines: [
      'Now is the winter of our discontent.',
      'A horse! A horse! My kingdom for a horse!',
    ],
  },
  {
    id: 'romeo-and-juliet',
    serial: 'SP-1594-R&J',
    title: 'Romeo and Juliet',
    genre: 'tragedy',
    yearWritten: 1594,
    acts: 5,
    characterCount: 24,
    inFirstFolio: true,
    source: "Arthur Brooke’s The Tragical History of Romeus and Juliet (1562)",
    approximateRuntime: 165,
    notableLines: [
      'But, soft! What light through yonder window breaks?',
      'A plague o’ both your houses!',
    ],
    altTitles: ['R&J'],
  },
  {
    id: 'taming-of-the-shrew',
    serial: 'SP-1593-TOS',
    title: 'The Taming of the Shrew',
    genre: 'comedy',
    yearWritten: 1593,
    acts: 5,
    characterCount: 22,
    inFirstFolio: true,
    source: "Anonymous The Taming of a Shrew; Italian commedia traditions",
    approximateRuntime: 150,
    notableLines: [
      'Kiss me, Kate.',
      'Such duty as the subject owes the prince, even such a woman oweth to her husband.',
    ],
    altTitles: ['Shrew'],
  },
  {
    id: 'the-tempest',
    serial: 'SP-1611-TMP',
    title: 'The Tempest',
    genre: 'romance',
    yearWritten: 1611,
    acts: 5,
    characterCount: 17,
    inFirstFolio: true,
    source: "William Strachey’s Bermuda letter; Montaigne’s essays",
    approximateRuntime: 135,
    notableLines: [
      'We are such stuff as dreams are made on, and our little life is rounded with a sleep.',
      'O brave new world, that has such people in’t!',
    ],
    altTitles: ['Tempest'],
  },
  {
    id: 'timon-of-athens',
    serial: 'SP-1607-TIM',
    title: 'Timon of Athens',
    genre: 'tragedy',
    yearWritten: 1607,
    acts: 5,
    characterCount: 24,
    inFirstFolio: true,
    source: "Plutarch’s Lives (Antony); Lucian’s Timon",
    approximateRuntime: 165,
    notableLines: [
      'I am Misanthropos, and hate mankind.',
      'We have seen better days.',
    ],
  },
  {
    id: 'titus-andronicus',
    serial: 'SP-1592-TIT',
    title: 'Titus Andronicus',
    genre: 'tragedy',
    yearWritten: 1592,
    acts: 5,
    characterCount: 25,
    inFirstFolio: true,
    source: "Ovid’s Metamorphoses (Philomela); chapbook source",
    approximateRuntime: 165,
    notableLines: [
      'Vengeance is in my heart, death in my hand, blood and revenge are hammering in my head.',
      'These words are razors to my wounded heart.',
    ],
  },
  {
    id: 'troilus-and-cressida',
    serial: 'SP-1601-T&C',
    title: 'Troilus and Cressida',
    genre: 'tragedy',
    yearWritten: 1601,
    acts: 5,
    characterCount: 30,
    inFirstFolio: true,
    source: "Chaucer’s Troilus and Criseyde; Caxton’s Recuyell of the Histories of Troy",
    approximateRuntime: 180,
    notableLines: [
      'Take but degree away, untune that string, and hark, what discord follows.',
      'O, beauty, where is thy faith?',
    ],
  },
  {
    id: 'twelfth-night',
    serial: 'SP-1601-TN',
    title: 'Twelfth Night',
    genre: 'comedy',
    yearWritten: 1601,
    acts: 5,
    characterCount: 16,
    inFirstFolio: true,
    source: "Gl’Ingannati (1531); Barnabe Rich’s Apolonius and Silla",
    approximateRuntime: 150,
    notableLines: [
      'If music be the food of love, play on.',
      'Some are born great, some achieve greatness, and some have greatness thrust upon them.',
    ],
    altTitles: ['What You Will'],
  },
  {
    id: 'two-gentlemen-of-verona',
    serial: 'SP-1593-TGV',
    title: 'The Two Gentlemen of Verona',
    genre: 'comedy',
    yearWritten: 1593,
    acts: 5,
    characterCount: 17,
    inFirstFolio: true,
    source: "Montemayor’s Diana Enamorada (Spanish romance)",
    approximateRuntime: 135,
    notableLines: [
      'How use doth breed a habit in a man!',
      'Who is Silvia? What is she, that all our swains commend her?',
    ],
    altTitles: ['TGV'],
  },
  {
    id: 'winters-tale',
    serial: 'SP-1610-WT',
    title: "The Winter's Tale",
    genre: 'romance',
    yearWritten: 1610,
    acts: 5,
    characterCount: 26,
    inFirstFolio: true,
    source: "Robert Greene’s Pandosto (1588)",
    approximateRuntime: 180,
    notableLines: [
      'Exit, pursued by a bear.',
      'A sad tale’s best for winter.',
    ],
  },
  {
    id: 'edward-iii',
    serial: 'SP-1592-E3',
    title: 'Edward III',
    genre: 'apocrypha',
    yearWritten: 1592,
    acts: 5,
    characterCount: 28,
    inFirstFolio: false,
    source: "Holinshed’s Chronicles; Froissart’s Chronicles",
    approximateRuntime: 165,
    notableLines: [
      'Lilies that fester smell far worse than weeds.',
      'A pox of wrinkles!',
    ],
    altTitles: ['The Reign of King Edward III'],
  },
  {
    id: 'two-noble-kinsmen',
    serial: 'SP-1613-2NK',
    title: 'The Two Noble Kinsmen',
    genre: 'apocrypha',
    yearWritten: 1613,
    acts: 5,
    characterCount: 22,
    inFirstFolio: false,
    source: "Chaucer’s The Knight’s Tale (Canterbury Tales)",
    approximateRuntime: 165,
    notableLines: [
      'O, never shall we two enjoy our lives, before we know ourselves.',
      'New plays and maidenheads are near akin.',
    ],
    altTitles: ['2NK', 'TNK'],
  },
]

export function getPlay(id: string): Play | undefined {
  return PLAYS.find((p) => p.id === id)
}

export function getPlayIds(): string[] {
  return PLAYS.map((p) => p.id)
}
