export enum CanonicalPlay {
  ALL_S_WELL_THAT_ENDS_WELL = 'ALL_S_WELL_THAT_ENDS_WELL',
  ANTONY_AND_CLEOPATRA = 'ANTONY_AND_CLEOPATRA',
  AS_YOU_LIKE_IT = 'AS_YOU_LIKE_IT',
  COMEDY_OF_ERRORS = 'COMEDY_OF_ERRORS',
  CORIOLANUS = 'CORIOLANUS',
  CYMBELINE = 'CYMBELINE',
  HAMLET = 'HAMLET',
  HENRY_IV_PART_1 = 'HENRY_IV_PART_1',
  HENRY_IV_PART_2 = 'HENRY_IV_PART_2',
  HENRY_V = 'HENRY_V',
  HENRY_VI_PART_1 = 'HENRY_VI_PART_1',
  HENRY_VI_PART_2 = 'HENRY_VI_PART_2',
  HENRY_VI_PART_3 = 'HENRY_VI_PART_3',
  HENRY_VIII = 'HENRY_VIII',
  JULIUS_CAESAR = 'JULIUS_CAESAR',
  KING_JOHN = 'KING_JOHN',
  KING_LEAR = 'KING_LEAR',
  LOVE_S_LABOUR_S_LOST = 'LOVE_S_LABOUR_S_LOST',
  MACBETH = 'MACBETH',
  MEASURE_FOR_MEASURE = 'MEASURE_FOR_MEASURE',
  MERCHANT_OF_VENICE = 'MERCHANT_OF_VENICE',
  MERRY_WIVES_OF_WINDSOR = 'MERRY_WIVES_OF_WINDSOR',
  MIDSUMMER_NIGHT_S_DREAM = 'MIDSUMMER_NIGHT_S_DREAM',
  MUCH_ADO_ABOUT_NOTHING = 'MUCH_ADO_ABOUT_NOTHING',
  OTHELLO = 'OTHELLO',
  RICHARD_II = 'RICHARD_II',
  RICHARD_III = 'RICHARD_III',
  ROMEO_AND_JULIET = 'ROMEO_AND_JULIET',
  TAMING_OF_THE_SHREW = 'TAMING_OF_THE_SHREW',
  TEMPEST = 'TEMPEST',
  TIMON_OF_ATHENS = 'TIMON_OF_ATHENS',
  TITUS_ANDRONICUS = 'TITUS_ANDRONICUS',
  TROILUS_AND_CRESSIDA = 'TROILUS_AND_CRESSIDA',
  TWELFTH_NIGHT = 'TWELFTH_NIGHT',
  TWO_GENTLEMEN_OF_VERONA = 'TWO_GENTLEMEN_OF_VERONA',
  WINTER_S_TALE = 'WINTER_S_TALE',
  PERICLES = 'PERICLES',
  EDWARD_III = 'EDWARD_III',
  TWO_NOBLE_KINSMEN = 'TWO_NOBLE_KINSMEN',
  OTHER = 'OTHER',
}

export const PLAY_TITLES: Record<CanonicalPlay, string> = {
  [CanonicalPlay.ALL_S_WELL_THAT_ENDS_WELL]: "All's Well That Ends Well",
  [CanonicalPlay.ANTONY_AND_CLEOPATRA]: 'Antony and Cleopatra',
  [CanonicalPlay.AS_YOU_LIKE_IT]: 'As You Like It',
  [CanonicalPlay.COMEDY_OF_ERRORS]: 'Comedy of Errors',
  [CanonicalPlay.CORIOLANUS]: 'Coriolanus',
  [CanonicalPlay.CYMBELINE]: 'Cymbeline',
  [CanonicalPlay.HAMLET]: 'Hamlet',
  [CanonicalPlay.HENRY_IV_PART_1]: 'Henry IV, Part 1',
  [CanonicalPlay.HENRY_IV_PART_2]: 'Henry IV, Part 2',
  [CanonicalPlay.HENRY_V]: 'Henry V',
  [CanonicalPlay.HENRY_VI_PART_1]: 'Henry VI, Part 1',
  [CanonicalPlay.HENRY_VI_PART_2]: 'Henry VI, Part 2',
  [CanonicalPlay.HENRY_VI_PART_3]: 'Henry VI, Part 3',
  [CanonicalPlay.HENRY_VIII]: 'Henry VIII',
  [CanonicalPlay.JULIUS_CAESAR]: 'Julius Caesar',
  [CanonicalPlay.KING_JOHN]: 'King John',
  [CanonicalPlay.KING_LEAR]: 'King Lear',
  [CanonicalPlay.LOVE_S_LABOUR_S_LOST]: "Love's Labour's Lost",
  [CanonicalPlay.MACBETH]: 'Macbeth',
  [CanonicalPlay.MEASURE_FOR_MEASURE]: 'Measure for Measure',
  [CanonicalPlay.MERCHANT_OF_VENICE]: 'Merchant of Venice',
  [CanonicalPlay.MERRY_WIVES_OF_WINDSOR]: 'Merry Wives of Windsor',
  [CanonicalPlay.MIDSUMMER_NIGHT_S_DREAM]: "Midsummer Night's Dream",
  [CanonicalPlay.MUCH_ADO_ABOUT_NOTHING]: 'Much Ado About Nothing',
  [CanonicalPlay.OTHELLO]: 'Othello',
  [CanonicalPlay.RICHARD_II]: 'Richard II',
  [CanonicalPlay.RICHARD_III]: 'Richard III',
  [CanonicalPlay.ROMEO_AND_JULIET]: 'Romeo and Juliet',
  [CanonicalPlay.TAMING_OF_THE_SHREW]: 'Taming of the Shrew',
  [CanonicalPlay.TEMPEST]: 'The Tempest',
  [CanonicalPlay.TIMON_OF_ATHENS]: 'Timon of Athens',
  [CanonicalPlay.TITUS_ANDRONICUS]: 'Titus Andronicus',
  [CanonicalPlay.TROILUS_AND_CRESSIDA]: 'Troilus and Cressida',
  [CanonicalPlay.TWELFTH_NIGHT]: 'Twelfth Night',
  [CanonicalPlay.TWO_GENTLEMEN_OF_VERONA]: 'Two Gentlemen of Verona',
  [CanonicalPlay.WINTER_S_TALE]: "Winter's Tale",
  [CanonicalPlay.PERICLES]: 'Pericles',
  [CanonicalPlay.EDWARD_III]: 'Edward III',
  [CanonicalPlay.TWO_NOBLE_KINSMEN]: 'Two Noble Kinsmen',
  [CanonicalPlay.OTHER]: 'Other',
}

export const PLAY_OPTIONS = Object.entries(PLAY_TITLES).map(([value, label]) => ({
  value,
  label,
}))

export interface PlayAlias {
  pattern: string
  play: CanonicalPlay
  confidence: number
}

export const DEFAULT_ALIASES: PlayAlias[] = [
  {
    pattern: 'r\\s*[&+]\\s*j|romeo.*juliet',
    play: CanonicalPlay.ROMEO_AND_JULIET,
    confidence: 0.9,
  },
  {
    pattern: 'scottish\\s+play|the\\s+scottish\\s+play',
    play: CanonicalPlay.MACBETH,
    confidence: 0.95,
  },
  {
    pattern: '12th\\s+night|twelfth\\s+night',
    play: CanonicalPlay.TWELFTH_NIGHT,
    confidence: 0.9,
  },
  {
    pattern: 'midsummer|midsummer.*dream|mnd',
    play: CanonicalPlay.MIDSUMMER_NIGHT_S_DREAM,
    confidence: 0.85,
  },
  {
    pattern: 'much\\s+ado',
    play: CanonicalPlay.MUCH_ADO_ABOUT_NOTHING,
    confidence: 0.9,
  },
  {
    pattern: 'merchant.*venice|mov',
    play: CanonicalPlay.MERCHANT_OF_VENICE,
    confidence: 0.85,
  },
  {
    pattern: 'taming.*shrew',
    play: CanonicalPlay.TAMING_OF_THE_SHREW,
    confidence: 0.9,
  },
  {
    pattern: 'as\\s+you\\s+like\\s+it|ayli',
    play: CanonicalPlay.AS_YOU_LIKE_IT,
    confidence: 0.9,
  },
  {
    pattern: "all.*s\\s+well|awew",
    play: CanonicalPlay.ALL_S_WELL_THAT_ENDS_WELL,
    confidence: 0.85,
  },
  {
    pattern: 'winter.*s\\s+tale|wt',
    play: CanonicalPlay.WINTER_S_TALE,
    confidence: 0.85,
  },
]
