name: Scrape Shakespeare Productions

on:
  schedule:
    - cron: "15 3 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    # Job-level secrets (configure these in the repository settings)
    #env:
    #  DATABASE_URL: 
    #  NEXTAUTH_SECRET: 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Generate Prisma client
        run: pnpm prisma generate
          
      - name: Run scraper
        run: pnpm scrape
          
      - name: Check scraping results
        run: echo "Scraping completed"
